// ============================================================
// Mock Data for TalentBoard AI
// Realistic data used across all screens for demonstration
// ============================================================

// ============================================================
// User Profile
// ============================================================
export const mockUser = {
  id: 'usr_01',
  fullName: 'Alex Johnson',
  email: 'alex.johnson@gmail.com',
  username: 'alexjohnson',
  professionalTitle: 'Senior Frontend Engineer',
  bio: 'Passionate frontend engineer with 6+ years of experience building scalable web applications. Specializing in React, TypeScript, and design systems. Previously at Stripe and Shopify.',
  experienceLevel: 'senior' as const,
  careerPath: 'Software Engineering',
  targetRole: 'Staff Frontend Engineer',
  location: 'San Francisco, CA',
  linkedinUrl: 'https://linkedin.com/in/alexjohnson',
  githubUrl: 'https://github.com/alexjohnson',
  websiteUrl: 'https://alexjohnson.dev',
  avatarUrl: '/images/avatar.jpg',
  resumeUrl: '/resumes/alex-johnson-resume.pdf',
  onboardingComplete: true,
  joinedDate: '2024-08-15',
};

// ============================================================
// Applications
// ============================================================
export const mockApplications = [
  {
    id: 'app_01',
    companyName: 'Stripe',
    jobTitle: 'Senior Frontend Engineer',
    location: 'San Francisco, CA (Hybrid)',
    jobUrl: 'https://stripe.com/jobs/frontend',
    status: 'interview' as const,
    priority: 'high' as const,
    salaryMin: 180000,
    salaryMax: 220000,
    salaryCurrency: 'USD',
    cvVersionId: 'cv_01',
    portfolioSubmitted: true,
    dateApplied: '2024-10-15',
    followUpDate: '2024-10-28',
    notes: 'Had a great initial call with the hiring manager. Technical round scheduled for next week.',
    source: 'referral' as const,
    contactName: 'Sarah Chen',
    contactEmail: 'sarah.c@stripe.com',
    kanbanOrder: 1,
    createdAt: '2024-10-14T10:00:00Z',
    updatedAt: '2024-10-20T14:30:00Z',
  },
  {
    id: 'app_02',
    companyName: 'Vercel',
    jobTitle: 'Product Designer',
    location: 'Remote (US)',
    jobUrl: 'https://vercel.com/careers/designer',
    status: 'screening' as const,
    priority: 'high' as const,
    salaryMin: 160000,
    salaryMax: 200000,
    salaryCurrency: 'USD',
    cvVersionId: 'cv_02',
    portfolioSubmitted: true,
    dateApplied: '2024-10-18',
    followUpDate: '2024-10-30',
    notes: 'Portfolio review stage. Submitted case study on design system project.',
    source: 'linkedin' as const,
    contactName: 'Mike Torres',
    contactEmail: 'mike@vercel.com',
    kanbanOrder: 1,
    createdAt: '2024-10-18T09:00:00Z',
    updatedAt: '2024-10-22T11:00:00Z',
  },
  {
    id: 'app_03',
    companyName: 'Linear',
    jobTitle: 'UI Engineer',
    location: 'Remote (Global)',
    jobUrl: 'https://linear.app/careers',
    status: 'applied' as const,
    priority: 'medium' as const,
    salaryMin: 150000,
    salaryMax: 190000,
    salaryCurrency: 'USD',
    cvVersionId: 'cv_01',
    portfolioSubmitted: false,
    dateApplied: '2024-10-24',
    followUpDate: '2024-11-04',
    notes: 'Applied through their website. Strong match with their tech stack.',
    source: 'company' as const,
    contactName: '',
    contactEmail: '',
    kanbanOrder: 2,
    createdAt: '2024-10-24T08:00:00Z',
    updatedAt: '2024-10-24T08:00:00Z',
  },
  {
    id: 'app_04',
    companyName: 'OpenAI',
    jobTitle: 'Design Technologist',
    location: 'San Francisco, CA',
    jobUrl: 'https://openai.com/careers',
    status: 'screening' as const,
    priority: 'high' as const,
    salaryMin: 200000,
    salaryMax: 280000,
    salaryCurrency: 'USD',
    cvVersionId: 'cv_01',
    portfolioSubmitted: true,
    dateApplied: '2024-10-22',
    followUpDate: '2024-11-01',
    notes: 'Exciting role combining design and engineering. AI experience is a plus.',
    source: 'linkedin' as const,
    contactName: 'David Park',
    contactEmail: 'david.p@openai.com',
    kanbanOrder: 2,
    createdAt: '2024-10-22T14:00:00Z',
    updatedAt: '2024-10-25T09:00:00Z',
  },
  {
    id: 'app_05',
    companyName: 'Notion',
    jobTitle: 'Senior Software Engineer',
    location: 'San Francisco, CA (Hybrid)',
    jobUrl: 'https://notion.so/careers',
    status: 'offer' as const,
    priority: 'high' as const,
    salaryMin: 190000,
    salaryMax: 230000,
    salaryCurrency: 'USD',
    cvVersionId: 'cv_01',
    portfolioSubmitted: true,
    dateApplied: '2024-09-28',
    followUpDate: null,
    notes: 'Received offer! $210K base + equity. Need to respond by Nov 5.',
    source: 'referral' as const,
    contactName: 'Emily Zhang',
    contactEmail: 'emily.z@notion.so',
    kanbanOrder: 1,
    createdAt: '2024-09-28T10:00:00Z',
    updatedAt: '2024-10-27T16:00:00Z',
  },
  {
    id: 'app_06',
    companyName: 'Figma',
    jobTitle: 'Frontend Engineer',
    location: 'San Francisco, CA',
    jobUrl: 'https://figma.com/careers',
    status: 'rejected' as const,
    priority: 'medium' as const,
    salaryMin: 170000,
    salaryMax: 210000,
    salaryCurrency: 'USD',
    cvVersionId: 'cv_01',
    portfolioSubmitted: true,
    dateApplied: '2024-09-15',
    followUpDate: null,
    notes: 'Rejected after final round. Feedback: strong technical skills but looking for more WebGL experience.',
    source: 'company' as const,
    contactName: 'Lisa Wang',
    contactEmail: 'lisa@figma.com',
    kanbanOrder: 1,
    createdAt: '2024-09-15T09:00:00Z',
    updatedAt: '2024-10-10T11:00:00Z',
  },
  {
    id: 'app_07',
    companyName: 'Ramp',
    jobTitle: 'Staff Engineer, Platform',
    location: 'New York, NY (Hybrid)',
    jobUrl: 'https://ramp.com/careers',
    status: 'applied' as const,
    priority: 'medium' as const,
    salaryMin: 200000,
    salaryMax: 260000,
    salaryCurrency: 'USD',
    cvVersionId: 'cv_01',
    portfolioSubmitted: false,
    dateApplied: '2024-10-26',
    followUpDate: '2024-11-06',
    notes: 'Interesting fintech role. Strong match with platform engineering experience.',
    source: 'linkedin' as const,
    contactName: '',
    contactEmail: '',
    kanbanOrder: 3,
    createdAt: '2024-10-26T15:00:00Z',
    updatedAt: '2024-10-26T15:00:00Z',
  },
  {
    id: 'app_08',
    companyName: 'Shopify',
    jobTitle: 'Senior Frontend Developer',
    location: 'Remote (Americas)',
    jobUrl: 'https://shopify.com/careers',
    status: 'interview' as const,
    priority: 'medium' as const,
    salaryMin: 165000,
    salaryMax: 200000,
    salaryCurrency: 'USD',
    cvVersionId: 'cv_02',
    portfolioSubmitted: true,
    dateApplied: '2024-10-10',
    followUpDate: '2024-10-29',
    notes: 'Past final round interview. Awaiting panel decision.',
    source: 'indeed' as const,
    contactName: 'James Miller',
    contactEmail: 'james.m@shopify.com',
    kanbanOrder: 2,
    createdAt: '2024-10-10T11:00:00Z',
    updatedAt: '2024-10-25T10:00:00Z',
  },
  {
    id: 'app_09',
    companyName: 'Supabase',
    jobTitle: 'Frontend Engineer',
    location: 'Remote (Global)',
    jobUrl: 'https://supabase.com/careers',
    status: 'saved' as const,
    priority: 'low' as const,
    salaryMin: 140000,
    salaryMax: 180000,
    salaryCurrency: 'USD',
    cvVersionId: null,
    portfolioSubmitted: false,
    dateApplied: null,
    followUpDate: null,
    notes: 'Great company culture. Open-source focused. Will apply next week.',
    source: 'company' as const,
    contactName: '',
    contactEmail: '',
    kanbanOrder: 1,
    createdAt: '2024-10-27T08:00:00Z',
    updatedAt: '2024-10-27T08:00:00Z',
  },
  {
    id: 'app_10',
    companyName: 'Datadog',
    jobTitle: 'Senior UI Engineer',
    location: 'New York, NY',
    jobUrl: 'https://datadoghq.com/careers',
    status: 'follow_up' as const,
    priority: 'medium' as const,
    salaryMin: 175000,
    salaryMax: 215000,
    salaryCurrency: 'USD',
    cvVersionId: 'cv_01',
    portfolioSubmitted: true,
    dateApplied: '2024-10-05',
    followUpDate: '2024-10-28',
    notes: 'No response after initial application. Need to follow up with recruiter.',
    source: 'glassdoor' as const,
    contactName: '',
    contactEmail: '',
    kanbanOrder: 1,
    createdAt: '2024-10-05T09:00:00Z',
    updatedAt: '2024-10-20T08:00:00Z',
  },
  {
    id: 'app_11',
    companyName: 'Anthropic',
    jobTitle: 'Product Engineer',
    location: 'San Francisco, CA',
    jobUrl: 'https://anthropic.com/careers',
    status: 'applied' as const,
    priority: 'high' as const,
    salaryMin: 210000,
    salaryMax: 300000,
    salaryCurrency: 'USD',
    cvVersionId: 'cv_01',
    portfolioSubmitted: true,
    dateApplied: '2024-10-25',
    followUpDate: '2024-11-05',
    notes: 'Dream role in AI safety. Applied with tailored resume emphasizing AI/ML projects.',
    source: 'company' as const,
    contactName: '',
    contactEmail: '',
    kanbanOrder: 4,
    createdAt: '2024-10-25T16:00:00Z',
    updatedAt: '2024-10-25T16:00:00Z',
  },
  {
    id: 'app_12',
    companyName: 'Airbnb',
    jobTitle: 'Staff Frontend Engineer',
    location: 'San Francisco, CA (Hybrid)',
    jobUrl: 'https://airbnb.com/careers',
    status: 'interview' as const,
    priority: 'high' as const,
    salaryMin: 220000,
    salaryMax: 280000,
    salaryCurrency: 'USD',
    cvVersionId: 'cv_01',
    portfolioSubmitted: true,
    dateApplied: '2024-10-08',
    followUpDate: '2024-10-30',
    notes: 'System design round completed. Behavioral round next Tuesday.',
    source: 'referral' as const,
    contactName: 'Nina Patel',
    contactEmail: 'nina.p@airbnb.com',
    kanbanOrder: 3,
    createdAt: '2024-10-08T10:00:00Z',
    updatedAt: '2024-10-26T15:00:00Z',
  },
];

// ============================================================
// Projects
// ============================================================
export const mockProjects = [
  {
    id: 'proj_01',
    title: 'TalentBoard AI',
    slug: 'talentboard-ai',
    category: 'web' as const,
    description: 'An intelligent career management platform that helps job seekers organize applications, optimize resumes, and prepare for interviews using AI.',
    businessProblem: 'Job seekers struggle with managing applications across multiple platforms, leading to missed opportunities and disorganized job searches.',
    solution: 'Built a centralized career OS with AI-powered resume optimization, interview preparation, and analytics dashboard.',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Supabase', 'OpenAI API'],
    skillsUsed: ['React', 'PostgreSQL', 'AI Integration', 'UI/UX Design'],
    githubUrl: 'https://github.com/alexjohnson/talentboard-ai',
    demoUrl: 'https://talentboard.ai',
    dashboardUrl: '',
    documentationUrl: 'https://docs.talentboard.ai',
    imageUrl: '/images/projects/talentboard.png',
    images: ['/images/projects/talentboard-dash.png', '/images/projects/talentboard-kanban.png'],
    isFeatured: true,
    displayOrder: 1,
    status: 'published' as const,
    createdAt: '2024-09-01T10:00:00Z',
    updatedAt: '2024-10-25T14:00:00Z',
  },
  {
    id: 'proj_02',
    title: 'FinFlow Dashboard',
    slug: 'finflow-dashboard',
    category: 'data' as const,
    description: 'A real-time financial analytics dashboard built for fintech startups to monitor transactions, revenue, and customer metrics.',
    businessProblem: 'Fintech startups lack affordable, real-time analytics tools that provide actionable insights from transaction data.',
    solution: 'Created a streaming analytics dashboard with D3.js visualizations, real-time WebSocket updates, and customizable KPI tracking.',
    technologies: ['React', 'D3.js', 'Node.js', 'PostgreSQL', 'WebSocket'],
    skillsUsed: ['Data Visualization', 'Backend Development', 'Real-time Systems'],
    githubUrl: 'https://github.com/alexjohnson/finflow',
    demoUrl: 'https://finflow-demo.vercel.app',
    dashboardUrl: '',
    documentationUrl: '',
    imageUrl: '/images/projects/finflow.png',
    images: [],
    isFeatured: true,
    displayOrder: 2,
    status: 'published' as const,
    createdAt: '2024-07-15T10:00:00Z',
    updatedAt: '2024-09-20T14:00:00Z',
  },
  {
    id: 'proj_03',
    title: 'ShopSmart AI',
    slug: 'shopsmart-ai',
    category: 'ai' as const,
    description: 'An AI-powered e-commerce recommendation engine that personalizes product suggestions based on browsing behavior and purchase history.',
    businessProblem: 'E-commerce platforms lose 70% of potential sales due to poor product recommendations and lack of personalization.',
    solution: 'Built a collaborative filtering engine with transformer-based embeddings that increased conversion rates by 34%.',
    technologies: ['Python', 'TensorFlow', 'FastAPI', 'Redis', 'React'],
    skillsUsed: ['Machine Learning', 'API Development', 'Python', 'React'],
    githubUrl: 'https://github.com/alexjohnson/shopsmart',
    demoUrl: 'https://shopsmart-demo.vercel.app',
    dashboardUrl: '',
    documentationUrl: '',
    imageUrl: '/images/projects/shopsmart.png',
    images: [],
    isFeatured: true,
    displayOrder: 3,
    status: 'published' as const,
    createdAt: '2024-05-10T10:00:00Z',
    updatedAt: '2024-08-15T14:00:00Z',
  },
  {
    id: 'proj_04',
    title: 'DevBoard',
    slug: 'devboard',
    category: 'web' as const,
    description: 'A developer productivity dashboard that aggregates GitHub activity, CI/CD pipelines, and team metrics in one view.',
    businessProblem: 'Engineering managers spend hours checking multiple tools (GitHub, Jira, CI systems) for team status updates.',
    solution: 'Unified dashboard pulling data from GitHub API, Jenkins, and Jira with customizable widgets and alert thresholds.',
    technologies: ['Next.js', 'GraphQL', 'Prisma', 'Chart.js'],
    skillsUsed: ['Full-Stack Development', 'API Integration', 'Data Visualization'],
    githubUrl: 'https://github.com/alexjohnson/devboard',
    demoUrl: '',
    dashboardUrl: '',
    documentationUrl: '',
    imageUrl: '/images/projects/devboard.png',
    images: [],
    isFeatured: false,
    displayOrder: 4,
    status: 'published' as const,
    createdAt: '2024-03-20T10:00:00Z',
    updatedAt: '2024-06-10T14:00:00Z',
  },
  {
    id: 'proj_05',
    title: 'HealthPulse Mobile',
    slug: 'healthpulse',
    category: 'mobile' as const,
    description: 'A cross-platform health tracking app that monitors fitness goals, sleep patterns, and nutrition with AI-powered recommendations.',
    businessProblem: 'Existing health apps are fragmented — users need separate apps for fitness, sleep, and nutrition tracking.',
    solution: 'Built a unified health companion with React Native, integrating Apple HealthKit and Google Fit APIs.',
    technologies: ['React Native', 'TypeScript', 'Firebase', 'TensorFlow Lite'],
    skillsUsed: ['Mobile Development', 'React Native', 'Health APIs'],
    githubUrl: 'https://github.com/alexjohnson/healthpulse',
    demoUrl: '',
    dashboardUrl: '',
    documentationUrl: '',
    imageUrl: '/images/projects/healthpulse.png',
    images: [],
    isFeatured: false,
    displayOrder: 5,
    status: 'published' as const,
    createdAt: '2024-01-10T10:00:00Z',
    updatedAt: '2024-04-15T14:00:00Z',
  },
  {
    id: 'proj_06',
    title: 'CloudConfig',
    slug: 'cloudconfig',
    category: 'devops' as const,
    description: 'Infrastructure-as-code platform for managing multi-cloud deployments with visual topology mapping.',
    businessProblem: 'DevOps teams struggle to visualize and manage infrastructure across AWS, GCP, and Azure.',
    solution: 'Built a visual IaC editor with Terraform integration, cost estimation, and drift detection.',
    technologies: ['Go', 'React', 'Terraform', 'AWS SDK', 'Docker'],
    skillsUsed: ['DevOps', 'Cloud Architecture', 'Go', 'React'],
    githubUrl: 'https://github.com/alexjohnson/cloudconfig',
    demoUrl: '',
    dashboardUrl: '',
    documentationUrl: '',
    imageUrl: '/images/projects/cloudconfig.png',
    images: [],
    isFeatured: false,
    displayOrder: 6,
    status: 'draft' as const,
    createdAt: '2023-11-01T10:00:00Z',
    updatedAt: '2024-02-20T14:00:00Z',
  },
];

// ============================================================
// CV Versions
// ============================================================
export const mockCVVersions = [
  {
    id: 'cv_01',
    name: 'General SWE Resume',
    fileUrl: '/resumes/alex-johnson-swe.pdf',
    fileSize: '245 KB',
    isDefault: true,
    targetRole: 'Software Engineer',
    createdAt: '2024-09-01T10:00:00Z',
  },
  {
    id: 'cv_02',
    name: 'Frontend Specialist',
    fileUrl: '/resumes/alex-johnson-frontend.pdf',
    fileSize: '238 KB',
    isDefault: false,
    targetRole: 'Frontend Engineer',
    createdAt: '2024-10-05T14:00:00Z',
  },
  {
    id: 'cv_03',
    name: 'Design Engineering',
    fileUrl: '/resumes/alex-johnson-design-eng.pdf',
    fileSize: '252 KB',
    isDefault: false,
    targetRole: 'Design Technologist',
    createdAt: '2024-10-20T09:00:00Z',
  },
];

// ============================================================
// Interviews
// ============================================================
export const mockInterviews = [
  {
    id: 'int_01',
    applicationId: 'app_01',
    companyName: 'Stripe',
    jobTitle: 'Senior Frontend Engineer',
    type: 'technical' as const,
    round: 'Round 2',
    scheduledAt: '2024-10-29T14:00:00Z',
    location: 'Remote',
    meetingUrl: 'https://zoom.us/j/123456789',
    interviewerName: 'Sarah Chen',
    interviewerRole: 'Engineering Manager',
    notes: 'Focus on React performance, state management patterns, and system design.',
    status: 'scheduled' as const,
    outcome: 'pending' as const,
  },
  {
    id: 'int_02',
    applicationId: 'app_02',
    companyName: 'Vercel',
    jobTitle: 'Product Designer',
    type: 'culture' as const,
    round: 'Round 1',
    scheduledAt: '2024-10-30T10:30:00Z',
    location: 'Remote',
    meetingUrl: 'https://meet.google.com/abc-defg-hij',
    interviewerName: 'Mike Torres',
    interviewerRole: 'Head of Design',
    notes: 'Prepare case study walkthrough. Focus on design process and collaboration.',
    status: 'scheduled' as const,
    outcome: 'pending' as const,
  },
  {
    id: 'int_03',
    applicationId: 'app_12',
    companyName: 'Airbnb',
    jobTitle: 'Staff Frontend Engineer',
    type: 'behavioral' as const,
    round: 'Round 3',
    scheduledAt: '2024-11-01T11:00:00Z',
    location: 'On-site (SF)',
    meetingUrl: '',
    interviewerName: 'Nina Patel',
    interviewerRole: 'VP Engineering',
    notes: 'Behavioral round. Prepare STAR examples for leadership, conflict resolution, and technical mentoring.',
    status: 'scheduled' as const,
    outcome: 'pending' as const,
  },
  {
    id: 'int_04',
    applicationId: 'app_08',
    companyName: 'Shopify',
    jobTitle: 'Senior Frontend Developer',
    type: 'panel' as const,
    round: 'Final',
    scheduledAt: '2024-10-25T15:00:00Z',
    location: 'Remote',
    meetingUrl: 'https://zoom.us/j/987654321',
    interviewerName: 'James Miller',
    interviewerRole: 'Staff Engineer',
    notes: 'Final panel. Team fit discussion.',
    status: 'completed' as const,
    outcome: 'pending' as const,
  },
];

// ============================================================
// Notifications
// ============================================================
export const mockNotifications = [
  {
    id: 'notif_01',
    title: 'Interview Tomorrow',
    message: 'Your technical interview with Stripe is scheduled for tomorrow at 2:00 PM.',
    type: 'interview_reminder' as const,
    isRead: false,
    actionUrl: '/applications/app_01',
    scheduledFor: '2024-10-28T09:00:00Z',
    createdAt: '2024-10-28T09:00:00Z',
  },
  {
    id: 'notif_02',
    title: 'Follow-Up Due',
    message: 'It\'s been 7 days since you applied to Datadog. Consider sending a follow-up.',
    type: 'follow_up' as const,
    isRead: false,
    actionUrl: '/applications/app_10',
    scheduledFor: '2024-10-28T08:00:00Z',
    createdAt: '2024-10-28T08:00:00Z',
  },
  {
    id: 'notif_03',
    title: 'AI Insight: Resume Match',
    message: 'Your resume matches 92% of Frontend roles in Fintech. Consider adding Web3 keywords.',
    type: 'ai_insight' as const,
    isRead: false,
    actionUrl: '/ai/resume-optimizer',
    scheduledFor: null,
    createdAt: '2024-10-27T14:00:00Z',
  },
  {
    id: 'notif_04',
    title: 'Offer Deadline',
    message: 'Your offer from Notion expires on November 5th. 8 days remaining.',
    type: 'deadline' as const,
    isRead: false,
    actionUrl: '/applications/app_05',
    scheduledFor: '2024-10-27T10:00:00Z',
    createdAt: '2024-10-27T10:00:00Z',
  },
  {
    id: 'notif_05',
    title: 'New Application Tracked',
    message: 'You applied to Anthropic for Product Engineer. Good luck!',
    type: 'system' as const,
    isRead: true,
    actionUrl: '/applications/app_11',
    scheduledFor: null,
    createdAt: '2024-10-25T16:00:00Z',
  },
  {
    id: 'notif_06',
    title: 'Interview with Vercel',
    message: 'Culture fit interview with Vercel is on October 30 at 10:30 AM via Google Meet.',
    type: 'interview_reminder' as const,
    isRead: true,
    actionUrl: '/applications/app_02',
    scheduledFor: '2024-10-29T09:00:00Z',
    createdAt: '2024-10-25T09:00:00Z',
  },
  {
    id: 'notif_07',
    title: 'Weekly Report Ready',
    message: 'Your weekly career analytics report is ready. You applied to 4 positions this week.',
    type: 'system' as const,
    isRead: true,
    actionUrl: '/analytics',
    scheduledFor: null,
    createdAt: '2024-10-21T08:00:00Z',
  },
];

// ============================================================
// Skills
// ============================================================
export const mockSkills = [
  { id: 'sk_01', name: 'React', category: 'framework' as const, proficiency: 'expert' as const },
  { id: 'sk_02', name: 'TypeScript', category: 'language' as const, proficiency: 'expert' as const },
  { id: 'sk_03', name: 'Next.js', category: 'framework' as const, proficiency: 'advanced' as const },
  { id: 'sk_04', name: 'Node.js', category: 'framework' as const, proficiency: 'advanced' as const },
  { id: 'sk_05', name: 'Python', category: 'language' as const, proficiency: 'intermediate' as const },
  { id: 'sk_06', name: 'PostgreSQL', category: 'tool' as const, proficiency: 'advanced' as const },
  { id: 'sk_07', name: 'Tailwind CSS', category: 'framework' as const, proficiency: 'expert' as const },
  { id: 'sk_08', name: 'GraphQL', category: 'technical' as const, proficiency: 'advanced' as const },
  { id: 'sk_09', name: 'Docker', category: 'tool' as const, proficiency: 'intermediate' as const },
  { id: 'sk_10', name: 'AWS', category: 'tool' as const, proficiency: 'intermediate' as const },
  { id: 'sk_11', name: 'Figma', category: 'tool' as const, proficiency: 'advanced' as const },
  { id: 'sk_12', name: 'Git', category: 'tool' as const, proficiency: 'expert' as const },
  { id: 'sk_13', name: 'CI/CD', category: 'technical' as const, proficiency: 'advanced' as const },
  { id: 'sk_14', name: 'System Design', category: 'technical' as const, proficiency: 'advanced' as const },
  { id: 'sk_15', name: 'Leadership', category: 'soft' as const, proficiency: 'advanced' as const },
  { id: 'sk_16', name: 'Communication', category: 'soft' as const, proficiency: 'expert' as const },
  { id: 'sk_17', name: 'Problem Solving', category: 'soft' as const, proficiency: 'expert' as const },
  { id: 'sk_18', name: 'D3.js', category: 'framework' as const, proficiency: 'intermediate' as const },
  { id: 'sk_19', name: 'Redux', category: 'framework' as const, proficiency: 'advanced' as const },
  { id: 'sk_20', name: 'REST APIs', category: 'technical' as const, proficiency: 'expert' as const },
  { id: 'sk_21', name: 'Testing (Jest/RTL)', category: 'tool' as const, proficiency: 'advanced' as const },
  { id: 'sk_22', name: 'Supabase', category: 'tool' as const, proficiency: 'advanced' as const },
  { id: 'sk_23', name: 'SQL', category: 'language' as const, proficiency: 'advanced' as const },
  { id: 'sk_24', name: 'AI/ML Fundamentals', category: 'technical' as const, proficiency: 'intermediate' as const },
];

// ============================================================
// Activity Log
// ============================================================
export const mockActivityLog = [
  { id: 'act_01', action: 'application_created', entityType: 'application', entityId: 'app_11', metadata: { company: 'Anthropic', role: 'Product Engineer' }, createdAt: '2024-10-25T16:00:00Z' },
  { id: 'act_02', action: 'status_changed', entityType: 'application', entityId: 'app_05', metadata: { company: 'Notion', oldStatus: 'interview', newStatus: 'offer' }, createdAt: '2024-10-27T16:00:00Z' },
  { id: 'act_03', action: 'ai_used', entityType: 'ai', entityId: 'gen_01', metadata: { type: 'resume_optimizer', company: 'Stripe' }, createdAt: '2024-10-26T11:00:00Z' },
  { id: 'act_04', action: 'project_added', entityType: 'project', entityId: 'proj_01', metadata: { title: 'TalentBoard AI' }, createdAt: '2024-10-25T10:00:00Z' },
  { id: 'act_05', action: 'application_created', entityType: 'application', entityId: 'app_07', metadata: { company: 'Ramp', role: 'Staff Engineer' }, createdAt: '2024-10-26T15:00:00Z' },
  { id: 'act_06', action: 'status_changed', entityType: 'application', entityId: 'app_01', metadata: { company: 'Stripe', oldStatus: 'screening', newStatus: 'interview' }, createdAt: '2024-10-20T14:30:00Z' },
  { id: 'act_07', action: 'ai_used', entityType: 'ai', entityId: 'gen_02', metadata: { type: 'interview_prep', company: 'Airbnb' }, createdAt: '2024-10-24T09:00:00Z' },
  { id: 'act_08', action: 'cv_uploaded', entityType: 'cv', entityId: 'cv_03', metadata: { name: 'Design Engineering' }, createdAt: '2024-10-20T09:00:00Z' },
];

// ============================================================
// Analytics Data
// ============================================================
export const mockAnalyticsData = {
  applicationsByWeek: [
    { week: 'Sep 2', count: 2 },
    { week: 'Sep 9', count: 1 },
    { week: 'Sep 16', count: 3 },
    { week: 'Sep 23', count: 1 },
    { week: 'Sep 30', count: 4 },
    { week: 'Oct 7', count: 3 },
    { week: 'Oct 14', count: 5 },
    { week: 'Oct 21', count: 8 },
  ],
  statusDistribution: [
    { status: 'Applied', count: 24, color: '#4F46E5' },
    { status: 'Screening', count: 12, color: '#F59E0B' },
    { status: 'Interviewing', count: 8, color: '#06B6D4' },
    { status: 'Offer', count: 3, color: '#10B981' },
  ],
  sourcePerformance: [
    { source: 'LinkedIn', applied: 18, interviews: 5, rate: 28 },
    { source: 'Referral', applied: 8, interviews: 6, rate: 75 },
    { source: 'Company Site', applied: 12, interviews: 3, rate: 25 },
    { source: 'Indeed', applied: 5, interviews: 1, rate: 20 },
    { source: 'Glassdoor', applied: 4, interviews: 0, rate: 0 },
  ],
  monthlyTrend: [
    { month: 'Jun', applications: 8, interviews: 2, offers: 0 },
    { month: 'Jul', applications: 12, interviews: 3, offers: 0 },
    { month: 'Aug', applications: 15, interviews: 4, offers: 1 },
    { month: 'Sep', applications: 10, interviews: 5, offers: 1 },
    { month: 'Oct', applications: 20, interviews: 8, offers: 1 },
  ],
  topSkillsRequested: [
    { skill: 'React', count: 38, percentage: 81 },
    { skill: 'TypeScript', count: 35, percentage: 74 },
    { skill: 'Next.js', count: 22, percentage: 47 },
    { skill: 'Node.js', count: 18, percentage: 38 },
    { skill: 'GraphQL', count: 12, percentage: 26 },
    { skill: 'Python', count: 10, percentage: 21 },
    { skill: 'AWS', count: 8, percentage: 17 },
    { skill: 'Docker', count: 7, percentage: 15 },
  ],
  responseTimeBySource: [
    { source: 'Referral', avgDays: 3 },
    { source: 'LinkedIn', avgDays: 7 },
    { source: 'Company Site', avgDays: 10 },
    { source: 'Indeed', avgDays: 14 },
    { source: 'Glassdoor', avgDays: 12 },
  ],
};

// ============================================================
// Contacts (from public portfolio)
// ============================================================
export const mockContacts = [
  {
    id: 'cont_01',
    senderName: 'Rachel Kim',
    senderEmail: 'rachel.kim@techcorp.io',
    message: 'Hi Alex, I saw your portfolio and I\'m really impressed by the TalentBoard AI project. We\'re looking for a senior frontend engineer at TechCorp. Would you be open to chatting?',
    isRead: false,
    createdAt: '2024-10-27T15:00:00Z',
  },
  {
    id: 'cont_02',
    senderName: 'Marcus Johnson',
    senderEmail: 'marcus@startup.co',
    message: 'Great work on the FinFlow Dashboard! We\'re building something similar and would love to discuss a potential collaboration.',
    isRead: true,
    createdAt: '2024-10-25T11:00:00Z',
  },
];
